# Inspired by https://medium.com/@xiaolishen/develop-in-docker-a-node-backend-and-a-react-front-end-talking-to-each-other-5c522156f634
version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - app-network
    depends_on:
      - client
      - server
  server:
    env_file: .env
    container_name: rolocha-server
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db
  client:
    env_file: .env
    container_name: rolocha-client
    expose:
      - 4000
      - 6006
    ports:
      - 4000:4000
      - 6006:6006
    networks:
      - app-network
  db:
    image: mongo
    container_name: db
    env_file: .env
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
