# Inspired by https://medium.com/@xiaolishen/develop-in-docker-a-node-backend-and-a-react-front-end-talking-to-each-other-5c522156f634
version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - server

  server:
    container_name: nomus-server
    restart: always
    env_file: .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
