version: "3"

services:
  nginx:
    ports:
      - 1234:80
      - 1235:443
  server:
    build: ./server
    ports:
      - 3000:3000 # app server port
      - 9229:9229 # debugging port
    env_file: .env
    command: yarn dev
    volumes:
      # Mirror local code but not node_modules
      - /server/node_modules/
      - ./server:/server
  client:
    container_name: nomus-client
    build: ./client
    env_file: .env
    ports:
      - 4000 # webpack server port
    networks:
      - app-network
    command: yarn dev
    volumes:
      # Mirror local code but not node_modules
      - /client/node_modules/
      - ./client:/client
  db:
    container_name: db
    image: mongo
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
