version: "3"

services:
  nginx:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 1234:80
      - 1235:443
  server:
    build:
      context: ./server
      args:
        - ENV
    ports:
      - 9222:9222 # debugging port
    env_file: .env
    command: yarn dev
    volumes:
      # Mirror local code but not node_modules
      - /server/node_modules/
      - ./server:/server
  client:
    build:
      context: ./client
      args:
        - ENV
    env_file: .env
    command: yarn dev
    volumes:
      # Mirror local code but not node_modules
      - /client/node_modules/
      - ./client:/client
