version: "3"

services:
  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  server:
    image: 074552482398.dkr.ecr.us-east-1.amazonaws.com/nomus/server:production-latest
    restart: always
    command: yarn serve

  db:
    ports:
      - 27017:27017
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email bibek@nomus.me --agree-tos --no-eff-email --staging -d nomus.me -d www.nomus.me

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/nomus-web
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/nomus-web
      o: bind
