version: "3"

services:
  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  server:
    image: 074552482398.dkr.ecr.us-east-1.amazonaws.com/nomus/server:production-latest
    restart: always
    command: yarn serve
  # client is served from S3
  # db is on MongoDB Atlas
