version: "3"

services:
  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs

  server:
    image: 074552482398.dkr.ecr.us-east-1.amazonaws.com/nomus/server:production-latest
    restart: always
    command: yarn serve

  # client is served from S3
  # db is on MongoDB Atlas

  certbot:
    command:
      certonly --webroot --webroot-path=/var/www/html --email bibek@nomus.me
      --agree-tos --no-eff-email --staging -d nomus.me -d www.nomus.me
    container_name: certbot
    depends_on:
      - nginx
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt:rw
      - certbot-var:/var/lib/letsencrypt:rw
      - web-root:/var/www/html:rw

volumes:
  certbot-etc: {}
  certbot-var: {}
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/rolobot
      o: bind
