version: "3"

services:
  # db hosted in MDB Atlas

  nginx:
    restart: always
    ports:
      - 80:80
      - 443:443

  server:
    image: 074552482398.dkr.ecr.us-east-1.amazonaws.com/nomus/server:staging-latest
    restart: always
    command: yarn serve
